application: arbow
version: 1
runtime: python
api_version: 1

handlers:

- url: /messager/.*
  script: gae-messager.py

- url: /js
  static_dir: wiki/js

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /feeds/.*
  script: feed_douban.py

- url: /wiki/.*
  script: wiki/main.py

- url: .*
  script: wiki/main.py

